[package]
name = "fhe-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.7.4", default-features = false, features = ["shortint", "internal-keycache", "seeder_unix"] }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
