[build]
# ARM-optimierte Flags
rustflags = [
    "-C", "opt-level=z",          # Größenoptimierung
    "-C", "target-cpu=generic",   # Keine CPU-spezifischen Instruktionen
]

# Build Scripts extra schonen
[target.'cfg(all())']
rustflags = [
    "-C", "opt-level=0",          # Build scripts ohne Optimierungen
]

[profile.release]
opt-level = "z"
lto = false
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[profile.bench]
opt-level = 2
lto = false
codegen-units = 1
